/* Incremental mel spectrogram computation using CMSIS-DSP.
 *
 * Each call to mel_process_frame() accepts 256 new int16 samples (one hop),
 * computes a 512-point FFT over the 256-sample overlap + 256 new samples,
 * applies the sparse mel filterbank, normalizes to int8, and stores one
 * frame in the double-buffered output.
 *
 * The mel filterbank coefficients are auto-generated by the training
 * pipeline (training/export.py → mel_filterbank.h).
 */

#include "mel_spectrogram.h"
#include "mel_filterbank.h"
#include "arm_math.h"
#include <string.h>

/* ---- Internal state ---- */

/* Double-buffered mel spectrograms (row-major: [frame][mel_bin]) */
static int8_t melBufA[MEL_FRAMES * MEL_BINS];
static int8_t melBufB[MEL_FRAMES * MEL_BINS];
static int8_t *melActive = melBufA;   /* buffer being filled */
static int8_t *melReady  = melBufB;   /* buffer ready for inference */

/* Frame counter within active buffer */
static int melFrameIdx = 0;

/* Overlap buffer: last 256 samples from previous hop */
static int16_t overlapBuf[MEL_HOP];

/* FFT working buffer: 512 int16 values (CMSIS q15) */
static q15_t fftInput[MEL_FFT_SIZE];
static q15_t fftOutput[MEL_FFT_SIZE];

/* Magnitude spectrum (only need bins 0..256) */
static q15_t magBuf[MEL_FFT_SIZE / 2 + 1];

/* CMSIS-DSP RFFT instance */
static arm_rfft_instance_q15 rfftInst;
static uint8_t rfftInitDone = 0;

/* Normalization constants (from training data) */
static float normMin = -80.0f;
static float normRange = 80.0f;  /* normMax - normMin */


void mel_init(float nMin, float nMax)
{
    normMin = nMin;
    normRange = nMax - nMin;
    if (normRange < 1e-6f) normRange = 1.0f;

    memset(overlapBuf, 0, sizeof(overlapBuf));
    memset(melBufA, 0, sizeof(melBufA));
    memset(melBufB, 0, sizeof(melBufB));
    melActive = melBufA;
    melReady  = melBufB;
    melFrameIdx = 0;

    /* Initialize CMSIS-DSP RFFT for 512-point q15.
     * ifftFlag=0 (forward), bitReverseFlag=1 (enable bit-reversal). */
    if (!rfftInitDone) {
        arm_rfft_init_q15(&rfftInst, MEL_FFT_SIZE, 0, 1);
        rfftInitDone = 1;
    }
}

void mel_reset(void)
{
    memset(overlapBuf, 0, sizeof(overlapBuf));
    melFrameIdx = 0;
}

int mel_get_frame_count(void)
{
    return melFrameIdx;
}

int mel_process_frame(const int16_t *samples)
{
    if (melFrameIdx >= MEL_FRAMES)
        return -1;  /* buffer full */

    /* Build FFT input: [overlap(256) | new(256)] */
    memcpy(fftInput, overlapBuf, MEL_HOP * sizeof(q15_t));
    memcpy(fftInput + MEL_HOP, samples, MEL_HOP * sizeof(q15_t));

    /* Save new samples as next overlap */
    memcpy(overlapBuf, samples, MEL_HOP * sizeof(q15_t));

    /* Apply Hann window (CMSIS-DSP doesn't include one, so inline it).
     * Pre-computed as Q15: w[n] = 0.5 * (1 - cos(2*pi*n/(N-1)))
     * For efficiency, we approximate with a symmetric multiply. */
    for (int n = 0; n < MEL_FFT_SIZE; n++) {
        /* Hann coefficient in Q15: round(32767 * 0.5 * (1 - cos(2*pi*n/511))) */
        float w = 0.5f * (1.0f - arm_cos_f32(6.2831853f * (float)n / (float)(MEL_FFT_SIZE - 1)));
        q15_t wq = (q15_t)(w * 32767.0f);
        q15_t tmp;
        arm_mult_q15(&fftInput[n], &wq, &tmp, 1);
        fftInput[n] = tmp;
    }

    /* Compute 512-point real FFT */
    arm_rfft_q15(&rfftInst, fftInput, fftOutput);

    /* Compute magnitude spectrum: |X[k]| = sqrt(re^2 + im^2)
     * fftOutput is interleaved [re0, im0, re1, im1, ...] */
    arm_cmplx_mag_q15(fftOutput, magBuf, MEL_FFT_SIZE / 2);
    /* DC bin magnitude (im=0) */
    magBuf[MEL_FFT_SIZE / 2] = (fftOutput[1] < 0) ? -fftOutput[1] : fftOutput[1];

    /* Apply sparse mel filterbank and compute log-mel energies */
    int8_t *frameOut = &melActive[melFrameIdx * MEL_BINS];

    for (int m = 0; m < MEL_BINS; m++) {
        int count = mel_fb_count[m];
        const uint16_t *idx = mel_fb_indices[m];
        const int16_t  *wt  = mel_fb_weights[m];

        /* Accumulate: sum(mag[idx[j]] * weight[j]) in int32 */
        int32_t acc = 0;
        for (int j = 0; j < count; j++) {
            acc += (int32_t)magBuf[idx[j]] * (int32_t)wt[j];
        }

        /* Convert to float for log, then normalize to int8.
         * acc is in Q15*Q15 = Q30 domain, scale down. */
        float energy = (float)acc / (32767.0f * 32767.0f);
        if (energy < 1e-10f) energy = 1e-10f;

        /* Log-mel energy (dB-like, matches librosa log-power) */
        float logMel = 10.0f * log10f(energy);

        /* Normalize to [-128, 127] int8 range using training statistics */
        float normalized = (logMel - normMin) / normRange;  /* 0..1 */
        int32_t quantized = (int32_t)(normalized * 255.0f - 128.0f);
        if (quantized < -128) quantized = -128;
        if (quantized > 127) quantized = 127;
        frameOut[m] = (int8_t)quantized;
    }

    int written = melFrameIdx;
    melFrameIdx++;
    return written;
}

const int8_t *mel_get_buffer(void)
{
    /* Swap active/ready buffers */
    int8_t *completed = melActive;
    melActive = melReady;
    melReady = completed;
    melFrameIdx = 0;
    return completed;
}
