/* Incremental mel spectrogram computation using CMSIS-DSP float FFT.
 *
 * Each call to mel_process_frame() accepts 256 new int16 samples (one hop),
 * computes a 512-point FFT over the 256-sample overlap + 256 new samples,
 * applies the sparse mel filterbank, normalizes to int8, and stores one
 * frame in the double-buffered output.
 *
 * Uses arm_rfft_fast_f32 (float FFT) instead of arm_rfft_q15 to avoid
 * Q15 dynamic range loss from internal 1/N scaling.  The M33 FPU makes
 * float ops ~1 cycle, so performance is comparable to Q15.
 *
 * The mel filterbank coefficients are auto-generated by the training
 * pipeline (training/export.py -> mel_filterbank.h).
 */

#include "mel_spectrogram.h"
#include "mel_filterbank.h"
#include "arm_math.h"
#include <string.h>
#include <math.h>

/* Fast natural log approximation using IEEE 754 float bit manipulation.
 * Avoids newlib log10f dependency.  Max relative error ~0.4%,
 * more than adequate for mel spectrogram normalization. */
static inline float fast_lnf(float x)
{
    union { float f; uint32_t i; } vx = { .f = x };
    union { uint32_t i; float f; } mx = {
        .i = (vx.i & 0x007FFFFF) | 0x3f000000
    };
    float y = (float)vx.i;
    y *= 1.1920928955078125e-7f;   /* 1 / (1<<23) */
    return (y - 124.22551499f
            - 1.498030302f * mx.f
            - 1.72587999f / (0.3520887068f + mx.f))
           * 0.69314718f;           /* ln(2) */
}

/* ---- Internal state ---- */

/* Double-buffered mel spectrograms (row-major: [frame][mel_bin]) */
static int8_t melBufA[MEL_FRAMES * MEL_BINS];
static int8_t melBufB[MEL_FRAMES * MEL_BINS];
static int8_t *melActive = melBufA;   /* buffer being filled */
static int8_t *melReady  = melBufB;   /* buffer ready for inference */

/* Frame counter within active buffer */
static int melFrameIdx = 0;

/* Overlap buffer: last 256 samples from previous hop (kept as int16) */
static int16_t overlapBuf[MEL_HOP];

/* FFT working buffers (float32 for full dynamic range).
 * arm_rfft_fast_f32 outputs N values and modifies input in-place. */
static float32_t fftInput[MEL_FFT_SIZE];
static float32_t fftOutput[MEL_FFT_SIZE];

/* Magnitude spectrum (bins 0..N/2) */
static float32_t magBuf[MEL_FFT_SIZE / 2 + 1];

/* Pre-computed Hann window (float32) */
static float32_t hannWindow[MEL_FFT_SIZE];

/* CMSIS-DSP RFFT fast instance (float) */
static arm_rfft_fast_instance_f32 rfftInst;
static uint8_t rfftInitDone = 0;

/* Debug: signal chain peak values (updated every frame, readable externally) */
static volatile int16_t melDbgInMax = 0;
static volatile int16_t melDbgFftMax = 0;
static volatile int16_t melDbgMagMax = 0;

void mel_get_debug(int16_t *inMax, int16_t *fftMax, int16_t *magMax)
{
    *inMax = melDbgInMax;
    *fftMax = melDbgFftMax;
    *magMax = melDbgMagMax;
}

/* Normalization constants (from training data) */
static float normMin = -80.0f;
static float normRange = 80.0f;  /* normMax - normMin */

/* Log-domain gain compensation (nepers).
 * Compensates for the gap between device mic level and training data level.
 * Set via mel_set_gain_compensation(). */
static float melGainComp = 0.0f;

void mel_set_gain_compensation(float db)
{
    /* Convert dB to log-power offset: dB * ln(10) / 10 */
    melGainComp = db * 0.23026f;
}

void mel_init(float nMin, float nMax)
{
    normMin = nMin;
    normRange = nMax - nMin;
    if (normRange < 1e-6f) normRange = 1.0f;

    memset(overlapBuf, 0, sizeof(overlapBuf));
    memset(melBufA, 0, sizeof(melBufA));
    memset(melBufB, 0, sizeof(melBufB));
    melActive = melBufA;
    melReady  = melBufB;
    melFrameIdx = 0;

    /* Pre-compute Hann window as float32 */
    for (int n = 0; n < MEL_FFT_SIZE; n++) {
        hannWindow[n] = 0.5f * (1.0f - arm_cos_f32(
            6.2831853f * (float)n / (float)(MEL_FFT_SIZE - 1)));
    }

    /* Initialize CMSIS-DSP RFFT for 512-point float32. */
    if (!rfftInitDone) {
        arm_rfft_fast_init_f32(&rfftInst, MEL_FFT_SIZE);
        rfftInitDone = 1;
    }
}

void mel_reset(void)
{
    memset(overlapBuf, 0, sizeof(overlapBuf));
    melFrameIdx = 0;
}

int mel_get_frame_count(void)
{
    return melFrameIdx;
}

int mel_process_frame(const int16_t *samples)
{
    if (melFrameIdx >= MEL_FRAMES)
        return -1;  /* buffer full */

    /* Build FFT input: [overlap(256) | new(256)]
     * Convert int16 -> float normalized to [-1, 1] to match librosa. */
    const float scale = 1.0f / 32768.0f;
    for (int i = 0; i < MEL_HOP; i++)
        fftInput[i] = (float)overlapBuf[i] * scale;
    for (int i = 0; i < MEL_HOP; i++)
        fftInput[MEL_HOP + i] = (float)samples[i] * scale;

    /* Save new samples as next overlap */
    memcpy(overlapBuf, samples, MEL_HOP * sizeof(int16_t));

    /* Track max input sample (int16 value, for external debug) */
    {
        int16_t inMax = 0;
        for (int i = 0; i < MEL_HOP; i++) {
            int16_t a = samples[i] < 0 ? -samples[i] : samples[i];
            if (a > inMax) inMax = a;
        }
        melDbgInMax = inMax;
    }

    /* Apply pre-computed Hann window (float multiply) */
    arm_mult_f32(fftInput, hannWindow, fftInput, MEL_FFT_SIZE);

    /* Compute 512-point real FFT (float — NO internal scaling) */
    arm_rfft_fast_f32(&rfftInst, fftInput, fftOutput, 0);

    /* Compute magnitude spectrum.
     * arm_rfft_fast_f32 output format:
     *   [0] = X[0] real (DC),  [1] = X[N/2] real (Nyquist)
     *   [2k, 2k+1] = Re(X[k]), Im(X[k])  for k = 1..N/2-1 */
    magBuf[0] = fabsf(fftOutput[0]);                        /* DC bin */
    arm_cmplx_mag_f32(&fftOutput[2], &magBuf[1],
                       MEL_FFT_SIZE / 2 - 1);               /* bins 1..254 */
    magBuf[MEL_FFT_SIZE / 2] = fabsf(fftOutput[1]);         /* Nyquist bin */

    /* Track max FFT output and max magnitude (for external debug) */
    {
        float fftMax = 0.0f;
        for (int i = 0; i < MEL_FFT_SIZE; i++) {
            float a = fabsf(fftOutput[i]);
            if (a > fftMax) fftMax = a;
        }
        float magMax = 0.0f;
        for (int i = 0; i < MEL_FFT_SIZE / 2 + 1; i++) {
            if (magBuf[i] > magMax) magMax = magBuf[i];
        }
        /* Scale x1000 for int16 debug display (milli-units) */
        int32_t f = (int32_t)(fftMax * 1000.0f);
        int32_t m = (int32_t)(magMax * 1000.0f);
        melDbgFftMax = (int16_t)(f > 32767 ? 32767 : f);
        melDbgMagMax = (int16_t)(m > 32767 ? 32767 : m);
    }

    /* Apply sparse mel filterbank and compute log-mel energies.
     *
     * Training uses librosa.feature.melspectrogram (power=2) + np.log():
     *   mel_power = sum(|X[k]|^2 * w[k])
     *   log_mel = ln(mel_power + 1e-9)
     *
     * Float FFT magnitude is in natural scale (input normalized to [-1,1]
     * matches librosa).  No Q15 scaling compensation needed. */
    int8_t *frameOut = &melActive[melFrameIdx * MEL_BINS];

    for (int m = 0; m < MEL_BINS; m++) {
        int count = mel_fb_count[m];
        const uint16_t *idx = mel_fb_indices[m];
        const int16_t  *wt  = mel_fb_weights[m];

        float acc = 0.0f;
        for (int j = 0; j < count; j++) {
            float mag = magBuf[idx[j]];
            acc += mag * mag * (float)wt[j];
        }

        /* Undo int16 weight scaling (weights stored as int16 * MEL_FB_SCALE) */
        float energy = acc / MEL_FB_SCALE;

        float logMel = fast_lnf(energy + 1e-9f) + melGainComp;

        /* Normalize to [-128, 127] int8 range using training statistics */
        float normalized = (logMel - normMin) / normRange;  /* 0..1 */
        int32_t quantized = (int32_t)(normalized * 255.0f - 128.0f);
        if (quantized < -128) quantized = -128;
        if (quantized > 127) quantized = 127;
        frameOut[m] = (int8_t)quantized;
    }

    int written = melFrameIdx;
    melFrameIdx++;
    return written;
}

const int8_t *mel_get_buffer(void)
{
    /* Swap active/ready buffers */
    int8_t *completed = melActive;
    melActive = melReady;
    melReady = completed;
    melFrameIdx = 0;
    return completed;
}
