/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "quailtracker.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(quailtracker_Status, quailtracker_Status, 2)


PB_BIND(quailtracker_GpsFix, quailtracker_GpsFix, AUTO)


PB_BIND(quailtracker_AudioLevel, quailtracker_AudioLevel, AUTO)


PB_BIND(quailtracker_Detection, quailtracker_Detection, AUTO)


PB_BIND(quailtracker_RecordingState, quailtracker_RecordingState, AUTO)


PB_BIND(quailtracker_LogLine, quailtracker_LogLine, AUTO)


PB_BIND(quailtracker_HealthReport, quailtracker_HealthReport, 2)


PB_BIND(quailtracker_Command, quailtracker_Command, AUTO)


PB_BIND(quailtracker_CommandAck, quailtracker_CommandAck, AUTO)


PB_BIND(quailtracker_Subscribe, quailtracker_Subscribe, AUTO)


PB_BIND(quailtracker_Unsubscribe, quailtracker_Unsubscribe, AUTO)


PB_BIND(quailtracker_TimeWindow, quailtracker_TimeWindow, AUTO)


PB_BIND(quailtracker_Config, quailtracker_Config, 2)


PB_BIND(quailtracker_SetConfig, quailtracker_SetConfig, 2)


PB_BIND(quailtracker_OtaBegin, quailtracker_OtaBegin, AUTO)


PB_BIND(quailtracker_OtaData, quailtracker_OtaData, AUTO)


PB_BIND(quailtracker_OtaEnd, quailtracker_OtaEnd, AUTO)


PB_BIND(quailtracker_OtaCommit, quailtracker_OtaCommit, AUTO)


PB_BIND(quailtracker_OtaAbort, quailtracker_OtaAbort, AUTO)


PB_BIND(quailtracker_OtaRollback, quailtracker_OtaRollback, AUTO)


PB_BIND(quailtracker_OtaStatus, quailtracker_OtaStatus, AUTO)





