; ESP32-C3 Bridge — SPI slave + WiFi AP + Web Server
; Prototype on Seeed XIAO ESP32-C3

[platformio]
default_envs = esp32c3

[env:esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = espidf
monitor_speed = 115200
extra_scripts = pre:embed_html.py
build_flags =
    -DCONFIG_HTTPD_WS_SUPPORT=1
