/* Auto-generated by QuailTracker training pipeline — do not edit */
#ifndef MEL_FILTERBANK_H
#define MEL_FILTERBANK_H

#include <stdint.h>

#define MEL_FB_N_MELS  40
#define MEL_FB_N_FFT   512
#define MEL_FB_N_BINS  257
#define MEL_FB_SCALE   2292971.184947f

/* Mel bin 0: 3 coefficients */
static const uint16_t mel_fb_idx_0[] = { 11, 12, 13 };
static const int16_t  mel_fb_wt_0[]  = { 8064, 32258, 12351 };

/* Mel bin 1: 2 coefficients */
static const uint16_t mel_fb_idx_1[] = { 13, 14 };
static const int16_t  mel_fb_wt_1[]  = { 22050, 22559 };

/* Mel bin 2: 3 coefficients */
static const uint16_t mel_fb_idx_2[] = { 14, 15, 16 };
static const int16_t  mel_fb_wt_2[]  = { 11842, 32767, 8573 };

/* Mel bin 3: 3 coefficients */
static const uint16_t mel_fb_idx_3[] = { 15, 16, 17 };
static const int16_t  mel_fb_wt_3[]  = { 1634, 25828, 18780 };

/* Mel bin 4: 3 coefficients */
static const uint16_t mel_fb_idx_4[] = { 17, 18, 19 };
static const int16_t  mel_fb_wt_4[]  = { 15620, 28988, 4794 };

/* Mel bin 5: 3 coefficients */
static const uint16_t mel_fb_idx_5[] = { 18, 19, 20 };
static const int16_t  mel_fb_wt_5[]  = { 5413, 29606, 15002 };

/* Mel bin 6: 3 coefficients */
static const uint16_t mel_fb_idx_6[] = { 20, 21, 22 };
static const int16_t  mel_fb_wt_6[]  = { 19164, 25122, 1792 };

/* Mel bin 7: 3 coefficients */
static const uint16_t mel_fb_idx_7[] = { 21, 22, 23 };
static const int16_t  mel_fb_wt_7[]  = { 8426, 30608, 13324 };

/* Mel bin 8: 3 coefficients */
static const uint16_t mel_fb_idx_8[] = { 23, 24, 25 };
static const int16_t  mel_fb_wt_8[]  = { 17671, 23774, 5903 };

/* Mel bin 9: 4 coefficients */
static const uint16_t mel_fb_idx_9[] = { 24, 25, 26, 27 };
static const int16_t  mel_fb_wt_9[]  = { 5877, 22560, 17642, 2067 };

/* Mel bin 10: 4 coefficients */
static const uint16_t mel_fb_idx_10[] = { 26, 27, 28, 29 };
static const int16_t  mel_fb_wt_10[]  = { 9736, 24277, 14434, 860 };

/* Mel bin 11: 4 coefficients */
static const uint16_t mel_fb_idx_11[] = { 28, 29, 30, 31 };
static const int16_t  mel_fb_wt_11[]  = { 10990, 23663, 13385, 1554 };

/* Mel bin 12: 4 coefficients */
static const uint16_t mel_fb_idx_12[] = { 30, 31, 32, 33 };
static const int16_t  mel_fb_wt_12[]  = { 10345, 21390, 13884, 3572 };

/* Mel bin 13: 4 coefficients */
static const uint16_t mel_fb_idx_13[] = { 32, 33, 34, 35 };
static const int16_t  mel_fb_wt_13[]  = { 8362, 17988, 15451, 6464 };

/* Mel bin 14: 5 coefficients */
static const uint16_t mel_fb_idx_14[] = { 34, 35, 36, 37, 38 };
static const int16_t  mel_fb_wt_14[]  = { 5482, 13873, 17708, 9875, 2043 };

/* Mel bin 15: 5 coefficients */
static const uint16_t mel_fb_idx_15[] = { 36, 37, 38, 39, 40 };
static const int16_t  mel_fb_wt_15[]  = { 2052, 9365, 16677, 13539, 6712 };

/* Mel bin 16: 5 coefficients */
static const uint16_t mel_fb_idx_16[] = { 39, 40, 41, 42, 43 };
static const int16_t  mel_fb_wt_16[]  = { 4710, 11084, 17251, 11301, 5351 };

/* Mel bin 17: 7 coefficients */
static const uint16_t mel_fb_idx_17[] = { 41, 42, 43, 44, 45, 46, 47 };
static const int16_t  mel_fb_wt_17[]  = { 92, 5647, 11202, 15676, 10490, 5305, 119 };

/* Mel bin 18: 7 coefficients */
static const uint16_t mel_fb_idx_18[] = { 44, 45, 46, 47, 48, 49, 50 };
static const int16_t  mel_fb_wt_18[]  = { 486, 5328, 10169, 15010, 10706, 6187, 1667 };

/* Mel bin 19: 6 coefficients */
static const uint16_t mel_fb_idx_19[] = { 48, 49, 50, 51, 52, 53 };
static const int16_t  mel_fb_wt_19[]  = { 4121, 8341, 12560, 11631, 7692, 3753 };

/* Mel bin 20: 7 coefficients */
static const uint16_t mel_fb_idx_20[] = { 51, 52, 53, 54, 55, 56, 57 };
static const int16_t  mel_fb_wt_20[]  = { 2320, 5997, 9675, 13018, 9585, 6152, 2718 };

/* Mel bin 21: 8 coefficients */
static const uint16_t mel_fb_idx_21[] = { 54, 55, 56, 57, 58, 59, 60, 61 };
static const int16_t  mel_fb_wt_21[]  = { 150, 3355, 6560, 9765, 11681, 8689, 5697, 2705 };

/* Mel bin 22: 9 coefficients */
static const uint16_t mel_fb_idx_22[] = { 58, 59, 60, 61, 62, 63, 64, 65, 66 };
static const int16_t  mel_fb_wt_22[]  = { 581, 3374, 6167, 8961, 11236, 8629, 6021, 3413, 805 };

/* Mel bin 23: 10 coefficients */
static const uint16_t mel_fb_idx_23[] = { 62, 63, 64, 65, 66, 67, 68, 69, 70, 71 };
static const int16_t  mel_fb_wt_23[]  = { 233, 2667, 5102, 7537, 9971, 9153, 6880, 4607, 2334, 61 };

/* Mel bin 24: 10 coefficients */
static const uint16_t mel_fb_idx_24[] = { 67, 68, 69, 70, 71, 72, 73, 74, 75, 76 };
static const int16_t  mel_fb_wt_24[]  = { 1466, 3588, 5710, 7832, 9954, 8084, 6103, 4122, 2141, 160 };

/* Mel bin 25: 10 coefficients */
static const uint16_t mel_fb_idx_25[] = { 72, 73, 74, 75, 76, 77, 78, 79, 80, 81 };
static const int16_t  mel_fb_wt_25[]  = { 1799, 3648, 5497, 7347, 9196, 7759, 6033, 4306, 2580, 853 };

/* Mel bin 26: 11 coefficients */
static const uint16_t mel_fb_idx_26[] = { 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87 };
static const int16_t  mel_fb_wt_26[]  = { 1481, 3093, 4704, 6316, 7928, 7964, 6460, 4955, 3450, 1945, 441 };

/* Mel bin 27: 12 coefficients */
static const uint16_t mel_fb_idx_27[] = { 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93 };
static const int16_t  mel_fb_wt_27[]  = { 710, 2114, 3519, 4924, 6329, 7734, 7219, 5907, 4596, 3284, 1973, 661 };

/* Mel bin 28: 13 coefficients */
static const uint16_t mel_fb_idx_28[] = { 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100 };
static const int16_t  mel_fb_wt_28[]  = { 865, 2089, 3314, 4538, 5762, 6987, 7038, 5895, 4752, 3609, 2466, 1323, 180 };

/* Mel bin 29: 14 coefficients */
static const uint16_t mel_fb_idx_29[] = { 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107 };
static const int16_t  mel_fb_wt_29[]  = { 528, 1595, 2662, 3729, 4797, 5864, 6931, 6260, 5264, 4268, 3272, 2275, 1279, 283 };

/* Mel bin 30: 14 coefficients */
static const uint16_t mel_fb_idx_30[] = { 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114 };
static const int16_t  mel_fb_wt_30[]  = { 783, 1713, 2643, 3573, 4503, 5433, 6363, 6006, 5138, 4270, 3402, 2533, 1665, 797 };

/* Mel bin 31: 16 coefficients */
static const uint16_t mel_fb_idx_31[] = { 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123 };
static const int16_t  mel_fb_wt_31[]  = { 579, 1390, 2201, 3011, 3822, 4632, 5443, 6125, 5369, 4612, 3855, 3099, 2342, 1585, 828, 72 };

/* Mel bin 32: 17 coefficients */
static const uint16_t mel_fb_idx_32[] = { 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131 };
static const int16_t  mel_fb_wt_32[]  = { 57, 764, 1470, 2177, 2883, 3590, 4296, 5002, 5709, 5180, 4520, 3860, 3201, 2541, 1882, 1222, 563 };

/* Mel bin 33: 18 coefficients */
static const uint16_t mel_fb_idx_33[] = { 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141 };
static const int16_t  mel_fb_wt_33[]  = { 557, 1172, 1788, 2404, 3019, 3635, 4251, 4867, 5309, 4734, 4159, 3584, 3009, 2435, 1860, 1285, 710, 135 };

/* Mel bin 34: 20 coefficients */
static const uint16_t mel_fb_idx_34[] = { 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151 };
static const int16_t  mel_fb_wt_34[]  = { 78, 614, 1151, 1688, 2224, 2761, 3298, 3834, 4371, 4908, 4652, 4151, 3650, 3149, 2648, 2147, 1646, 1145, 644, 143 };

/* Mel bin 35: 21 coefficients */
static const uint16_t mel_fb_idx_35[] = { 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162 };
static const int16_t  mel_fb_wt_35[]  = { 357, 824, 1292, 1760, 2228, 2695, 3163, 3631, 4098, 4566, 4388, 3951, 3515, 3078, 2641, 2205, 1768, 1331, 895, 458, 21 };

/* Mel bin 36: 22 coefficients */
static const uint16_t mel_fb_idx_36[] = { 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173 };
static const int16_t  mel_fb_wt_36[]  = { 291, 698, 1106, 1514, 1921, 2329, 2736, 3144, 3552, 3959, 4367, 4026, 3646, 3265, 2885, 2504, 2123, 1743, 1362, 982, 601, 221 };

/* Mel bin 37: 23 coefficients */
static const uint16_t mel_fb_idx_37[] = { 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185 };
static const int16_t  mel_fb_wt_37[]  = { 337, 692, 1047, 1403, 1758, 2113, 2469, 2824, 3179, 3534, 3890, 3957, 3625, 3294, 2962, 2630, 2299, 1967, 1635, 1304, 972, 640, 309 };

/* Mel bin 38: 26 coefficients */
static const uint16_t mel_fb_idx_38[] = { 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199 };
static const int16_t  mel_fb_wt_38[]  = { 129, 439, 749, 1058, 1368, 1677, 1987, 2297, 2606, 2916, 3226, 3535, 3804, 3515, 3226, 2937, 2648, 2359, 2070, 1781, 1492, 1203, 914, 624, 335, 46 };

/* Mel bin 39: 28 coefficients */
static const uint16_t mel_fb_idx_39[] = { 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213 };
static const int16_t  mel_fb_wt_39[]  = { 18, 288, 558, 827, 1097, 1367, 1637, 1907, 2177, 2447, 2717, 2986, 3256, 3526, 3359, 3107, 2855, 2603, 2351, 2099, 1847, 1595, 1343, 1091, 839, 587, 335, 83 };

static const uint8_t mel_fb_count[MEL_FB_N_MELS] = {
  3, 2, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 7, 7, 6, 7, 8, 9, 10, 10, 10, 11, 12, 13, 14, 14, 16, 17, 18, 20, 21, 22, 23, 26, 28
};

static const uint16_t* const mel_fb_indices[MEL_FB_N_MELS] = {
  mel_fb_idx_0, mel_fb_idx_1, mel_fb_idx_2, mel_fb_idx_3, mel_fb_idx_4, mel_fb_idx_5, mel_fb_idx_6, mel_fb_idx_7, mel_fb_idx_8, mel_fb_idx_9, mel_fb_idx_10, mel_fb_idx_11, mel_fb_idx_12, mel_fb_idx_13, mel_fb_idx_14, mel_fb_idx_15, mel_fb_idx_16, mel_fb_idx_17, mel_fb_idx_18, mel_fb_idx_19, mel_fb_idx_20, mel_fb_idx_21, mel_fb_idx_22, mel_fb_idx_23, mel_fb_idx_24, mel_fb_idx_25, mel_fb_idx_26, mel_fb_idx_27, mel_fb_idx_28, mel_fb_idx_29, mel_fb_idx_30, mel_fb_idx_31, mel_fb_idx_32, mel_fb_idx_33, mel_fb_idx_34, mel_fb_idx_35, mel_fb_idx_36, mel_fb_idx_37, mel_fb_idx_38, mel_fb_idx_39
};

static const int16_t* const mel_fb_weights[MEL_FB_N_MELS] = {
  mel_fb_wt_0, mel_fb_wt_1, mel_fb_wt_2, mel_fb_wt_3, mel_fb_wt_4, mel_fb_wt_5, mel_fb_wt_6, mel_fb_wt_7, mel_fb_wt_8, mel_fb_wt_9, mel_fb_wt_10, mel_fb_wt_11, mel_fb_wt_12, mel_fb_wt_13, mel_fb_wt_14, mel_fb_wt_15, mel_fb_wt_16, mel_fb_wt_17, mel_fb_wt_18, mel_fb_wt_19, mel_fb_wt_20, mel_fb_wt_21, mel_fb_wt_22, mel_fb_wt_23, mel_fb_wt_24, mel_fb_wt_25, mel_fb_wt_26, mel_fb_wt_27, mel_fb_wt_28, mel_fb_wt_29, mel_fb_wt_30, mel_fb_wt_31, mel_fb_wt_32, mel_fb_wt_33, mel_fb_wt_34, mel_fb_wt_35, mel_fb_wt_36, mel_fb_wt_37, mel_fb_wt_38, mel_fb_wt_39
};

#endif /* MEL_FILTERBANK_H */
