/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_QUAILTRACKER_QUAILTRACKER_PB_H_INCLUDED
#define PB_QUAILTRACKER_QUAILTRACKER_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _quailtracker_CommandType {
    quailtracker_CommandType_CMD_NONE = 0,
    quailtracker_CommandType_CMD_REC_START = 1,
    quailtracker_CommandType_CMD_REC_STOP = 2,
    quailtracker_CommandType_CMD_REC_TOGGLE = 3,
    quailtracker_CommandType_CMD_SD_MOUNT = 10,
    quailtracker_CommandType_CMD_SD_EJECT = 11,
    quailtracker_CommandType_CMD_SD_FORMAT = 12,
    quailtracker_CommandType_CMD_GET_STATUS = 20,
    quailtracker_CommandType_CMD_GET_CONFIG = 21,
    quailtracker_CommandType_CMD_MODEL_RELOAD = 30,
    quailtracker_CommandType_CMD_MODEL_STATUS = 31,
    quailtracker_CommandType_CMD_DET_STATUS = 32,
    quailtracker_CommandType_CMD_SURVEY_START = 40,
    quailtracker_CommandType_CMD_SURVEY_STOP = 41,
    quailtracker_CommandType_CMD_SURVEY_CLEAR = 42,
    quailtracker_CommandType_CMD_LOGS_TOGGLE = 50
} quailtracker_CommandType;

/* Struct definitions */
typedef struct _quailtracker_Status {
    /* Battery */
    uint32_t battery_mv;
    uint32_t battery_pct; /* 0-100 */
    /* BLE */
    bool ble_ready;
    char ble_name[16];
    /* SD */
    bool sd_mounted;
    uint32_t sd_total_kb;
    uint32_t sd_free_kb;
    /* Recording */
    bool recording;
    char rec_filename[40];
    uint32_t rec_bytes;
    uint32_t rec_duration_s;
    uint32_t rec_overruns;
    uint32_t rec_format; /* 0=FLAC, 1=WAV */
    /* Detection */
    bool det_active;
    uint32_t det_windows;
    uint32_t det_hits;
    char det_last_species[32];
    bool model_loaded;
    uint32_t model_size;
    uint32_t model_labels;
    /* Environment */
    int32_t temperature_c100; /* hundredths of °C */
    uint32_t humidity_rh100; /* hundredths of %RH */
    /* Firmware */
    char firmware_version[16];
    char station_id[16];
} quailtracker_Status;

typedef struct _quailtracker_GpsFix {
    bool valid;
    uint32_t satellites;
    int32_t latitude_e7; /* degrees × 10^7 */
    int32_t longitude_e7;
    int32_t altitude_mm;
    uint32_t fix_type; /* 0=none, 1=2D, 2=3D */
    bool pps_synced;
    uint32_t pps_count;
    char utc_time[16]; /* YYYYMMDDHHMMSS */
} quailtracker_GpsFix;

typedef struct _quailtracker_AudioLevel {
    uint32_t peak; /* 0-32767 */
    uint32_t activity_pct; /* 0-100 */
    uint32_t clip_count;
    uint32_t buf_used;
    uint32_t buf_capacity;
} quailtracker_AudioLevel;

typedef struct _quailtracker_Detection {
    char species[32];
    uint32_t confidence; /* 0-100 */
    char utc_time[16];
    uint64_t window_sample;
} quailtracker_Detection;

typedef struct _quailtracker_RecordingState {
    bool active;
    char filename[40];
    uint32_t bytes_written;
    uint32_t duration_s;
    uint32_t overruns;
    uint32_t sd_free_kb;
} quailtracker_RecordingState;

typedef struct _quailtracker_LogLine {
    char text[128];
} quailtracker_LogLine;

typedef struct _quailtracker_Command {
    quailtracker_CommandType type;
} quailtracker_Command;

typedef struct _quailtracker_CommandAck {
    quailtracker_CommandType type;
    bool success;
    char error[32]; /* empty on success */
} quailtracker_CommandAck;

typedef struct _quailtracker_Subscribe {
    uint32_t topic; /* Topic enum value */
    uint32_t interval_ms; /* 0 = on-change only, >0 = periodic push */
} quailtracker_Subscribe;

typedef struct _quailtracker_Unsubscribe {
    uint32_t topic;
} quailtracker_Unsubscribe;

typedef struct _quailtracker_TimeWindow {
    uint32_t start_hhmm; /* e.g., 600 = 06:00 */
    uint32_t end_hhmm; /* e.g., 900 = 09:00 */
} quailtracker_TimeWindow;

typedef struct _quailtracker_Config {
    /* Audio */
    uint32_t gain; /* 0-24, 3dB steps */
    uint32_t bpf_low_hz;
    uint32_t bpf_high_hz;
    uint32_t sample_rate;
    uint32_t rec_format; /* 0=FLAC, 1=WAV */
    /* Station */
    char station_id[16];
    /* Amplitude trigger */
    bool trig_enabled;
    int32_t trig_db; /* -60 to 0 */
    uint32_t trig_pre_s; /* 0-30 */
    uint32_t trig_post_s; /* 0-60 */
    /* Battery */
    uint32_t low_bat_pct; /* 0-100 */
    bool auto_stop;
    /* Activity filter */
    uint32_t act_mode; /* 0-3 */
    uint32_t act_min_pct;
    uint32_t act_max_pct;
    uint32_t act_hold_s;
    /* Scheduling */
    bool sunrise_enabled;
    uint32_t sunrise_before;
    uint32_t sunrise_after;
    bool sunset_enabled;
    uint32_t sunset_before;
    uint32_t sunset_after;
    pb_size_t windows_count;
    quailtracker_TimeWindow windows[8]; /* max 8 */
    /* Detection */
    uint32_t mission_mode; /* 0=record, 1=detect, 2=both */
    uint32_t det_threshold; /* 0-100 */
    uint32_t det_step_s; /* 1-3 */
    /* Survey-in */
    int32_t survey_lat_e7;
    int32_t survey_lon_e7;
    int32_t survey_alt_mm;
    uint32_t survey_count;
} quailtracker_Config;

typedef struct _quailtracker_SetConfig {
    bool has_gain;
    uint32_t gain;
    bool has_bpf_low_hz;
    uint32_t bpf_low_hz;
    bool has_bpf_high_hz;
    uint32_t bpf_high_hz;
    bool has_rec_format;
    uint32_t rec_format;
    bool has_station_id;
    char station_id[16];
    bool has_trig_enabled;
    bool trig_enabled;
    bool has_trig_db;
    int32_t trig_db;
    bool has_trig_pre_s;
    uint32_t trig_pre_s;
    bool has_trig_post_s;
    uint32_t trig_post_s;
    bool has_low_bat_pct;
    uint32_t low_bat_pct;
    bool has_auto_stop;
    bool auto_stop;
    bool has_act_mode;
    uint32_t act_mode;
    bool has_act_min_pct;
    uint32_t act_min_pct;
    bool has_act_max_pct;
    uint32_t act_max_pct;
    bool has_act_hold_s;
    uint32_t act_hold_s;
    bool has_sunrise_enabled;
    bool sunrise_enabled;
    bool has_sunrise_before;
    uint32_t sunrise_before;
    bool has_sunrise_after;
    uint32_t sunrise_after;
    bool has_sunset_enabled;
    bool sunset_enabled;
    bool has_sunset_before;
    uint32_t sunset_before;
    bool has_sunset_after;
    uint32_t sunset_after;
    pb_size_t windows_count;
    quailtracker_TimeWindow windows[8];
    bool has_mission_mode;
    uint32_t mission_mode;
    bool has_det_threshold;
    uint32_t det_threshold;
    bool has_det_step_s;
    uint32_t det_step_s;
} quailtracker_SetConfig;

typedef struct _quailtracker_OtaBegin {
    uint32_t size_bytes;
    uint32_t crc32;
} quailtracker_OtaBegin;

typedef PB_BYTES_ARRAY_T(128) quailtracker_OtaData_chunk_t;
typedef struct _quailtracker_OtaData {
    quailtracker_OtaData_chunk_t chunk; /* raw firmware bytes, up to 128 per frame */
} quailtracker_OtaData;

typedef struct _quailtracker_OtaEnd {
    char dummy_field;
} quailtracker_OtaEnd;

typedef struct _quailtracker_OtaCommit {
    char dummy_field;
} quailtracker_OtaCommit;

typedef struct _quailtracker_OtaAbort {
    char dummy_field;
} quailtracker_OtaAbort;

typedef struct _quailtracker_OtaRollback {
    char dummy_field;
} quailtracker_OtaRollback;

typedef struct _quailtracker_OtaStatus {
    uint32_t state; /* 0=idle, 1=receiving, 2=complete */
    uint32_t bytes_received;
    uint32_t pages_written;
    uint32_t pages_total;
} quailtracker_OtaStatus;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _quailtracker_CommandType_MIN quailtracker_CommandType_CMD_NONE
#define _quailtracker_CommandType_MAX quailtracker_CommandType_CMD_LOGS_TOGGLE
#define _quailtracker_CommandType_ARRAYSIZE ((quailtracker_CommandType)(quailtracker_CommandType_CMD_LOGS_TOGGLE+1))







#define quailtracker_Command_type_ENUMTYPE quailtracker_CommandType

#define quailtracker_CommandAck_type_ENUMTYPE quailtracker_CommandType














/* Initializer values for message structs */
#define quailtracker_Status_init_default         {0, 0, 0, "", 0, 0, 0, 0, "", 0, 0, 0, 0, 0, 0, 0, "", 0, 0, 0, 0, 0, "", ""}
#define quailtracker_GpsFix_init_default         {0, 0, 0, 0, 0, 0, 0, 0, ""}
#define quailtracker_AudioLevel_init_default     {0, 0, 0, 0, 0}
#define quailtracker_Detection_init_default      {"", 0, "", 0}
#define quailtracker_RecordingState_init_default {0, "", 0, 0, 0, 0}
#define quailtracker_LogLine_init_default        {""}
#define quailtracker_Command_init_default        {_quailtracker_CommandType_MIN}
#define quailtracker_CommandAck_init_default     {_quailtracker_CommandType_MIN, 0, ""}
#define quailtracker_Subscribe_init_default      {0, 0}
#define quailtracker_Unsubscribe_init_default    {0}
#define quailtracker_TimeWindow_init_default     {0, 0}
#define quailtracker_Config_init_default         {0, 0, 0, 0, 0, "", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, {quailtracker_TimeWindow_init_default, quailtracker_TimeWindow_init_default, quailtracker_TimeWindow_init_default, quailtracker_TimeWindow_init_default, quailtracker_TimeWindow_init_default, quailtracker_TimeWindow_init_default, quailtracker_TimeWindow_init_default, quailtracker_TimeWindow_init_default}, 0, 0, 0, 0, 0, 0, 0}
#define quailtracker_SetConfig_init_default      {false, 0, false, 0, false, 0, false, 0, false, "", false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, 0, {quailtracker_TimeWindow_init_default, quailtracker_TimeWindow_init_default, quailtracker_TimeWindow_init_default, quailtracker_TimeWindow_init_default, quailtracker_TimeWindow_init_default, quailtracker_TimeWindow_init_default, quailtracker_TimeWindow_init_default, quailtracker_TimeWindow_init_default}, false, 0, false, 0, false, 0}
#define quailtracker_OtaBegin_init_default       {0, 0}
#define quailtracker_OtaData_init_default        {{0, {0}}}
#define quailtracker_OtaEnd_init_default         {0}
#define quailtracker_OtaCommit_init_default      {0}
#define quailtracker_OtaAbort_init_default       {0}
#define quailtracker_OtaRollback_init_default    {0}
#define quailtracker_OtaStatus_init_default      {0, 0, 0, 0}
#define quailtracker_Status_init_zero            {0, 0, 0, "", 0, 0, 0, 0, "", 0, 0, 0, 0, 0, 0, 0, "", 0, 0, 0, 0, 0, "", ""}
#define quailtracker_GpsFix_init_zero            {0, 0, 0, 0, 0, 0, 0, 0, ""}
#define quailtracker_AudioLevel_init_zero        {0, 0, 0, 0, 0}
#define quailtracker_Detection_init_zero         {"", 0, "", 0}
#define quailtracker_RecordingState_init_zero    {0, "", 0, 0, 0, 0}
#define quailtracker_LogLine_init_zero           {""}
#define quailtracker_Command_init_zero           {_quailtracker_CommandType_MIN}
#define quailtracker_CommandAck_init_zero        {_quailtracker_CommandType_MIN, 0, ""}
#define quailtracker_Subscribe_init_zero         {0, 0}
#define quailtracker_Unsubscribe_init_zero       {0}
#define quailtracker_TimeWindow_init_zero        {0, 0}
#define quailtracker_Config_init_zero            {0, 0, 0, 0, 0, "", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, {quailtracker_TimeWindow_init_zero, quailtracker_TimeWindow_init_zero, quailtracker_TimeWindow_init_zero, quailtracker_TimeWindow_init_zero, quailtracker_TimeWindow_init_zero, quailtracker_TimeWindow_init_zero, quailtracker_TimeWindow_init_zero, quailtracker_TimeWindow_init_zero}, 0, 0, 0, 0, 0, 0, 0}
#define quailtracker_SetConfig_init_zero         {false, 0, false, 0, false, 0, false, 0, false, "", false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, 0, {quailtracker_TimeWindow_init_zero, quailtracker_TimeWindow_init_zero, quailtracker_TimeWindow_init_zero, quailtracker_TimeWindow_init_zero, quailtracker_TimeWindow_init_zero, quailtracker_TimeWindow_init_zero, quailtracker_TimeWindow_init_zero, quailtracker_TimeWindow_init_zero}, false, 0, false, 0, false, 0}
#define quailtracker_OtaBegin_init_zero          {0, 0}
#define quailtracker_OtaData_init_zero           {{0, {0}}}
#define quailtracker_OtaEnd_init_zero            {0}
#define quailtracker_OtaCommit_init_zero         {0}
#define quailtracker_OtaAbort_init_zero          {0}
#define quailtracker_OtaRollback_init_zero       {0}
#define quailtracker_OtaStatus_init_zero         {0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define quailtracker_Status_battery_mv_tag       1
#define quailtracker_Status_battery_pct_tag      2
#define quailtracker_Status_ble_ready_tag        10
#define quailtracker_Status_ble_name_tag         11
#define quailtracker_Status_sd_mounted_tag       20
#define quailtracker_Status_sd_total_kb_tag      21
#define quailtracker_Status_sd_free_kb_tag       22
#define quailtracker_Status_recording_tag        30
#define quailtracker_Status_rec_filename_tag     31
#define quailtracker_Status_rec_bytes_tag        32
#define quailtracker_Status_rec_duration_s_tag   33
#define quailtracker_Status_rec_overruns_tag     34
#define quailtracker_Status_rec_format_tag       35
#define quailtracker_Status_det_active_tag       40
#define quailtracker_Status_det_windows_tag      41
#define quailtracker_Status_det_hits_tag         42
#define quailtracker_Status_det_last_species_tag 43
#define quailtracker_Status_model_loaded_tag     44
#define quailtracker_Status_model_size_tag       45
#define quailtracker_Status_model_labels_tag     46
#define quailtracker_Status_temperature_c100_tag 50
#define quailtracker_Status_humidity_rh100_tag   51
#define quailtracker_Status_firmware_version_tag 60
#define quailtracker_Status_station_id_tag       61
#define quailtracker_GpsFix_valid_tag            1
#define quailtracker_GpsFix_satellites_tag       2
#define quailtracker_GpsFix_latitude_e7_tag      3
#define quailtracker_GpsFix_longitude_e7_tag     4
#define quailtracker_GpsFix_altitude_mm_tag      5
#define quailtracker_GpsFix_fix_type_tag         6
#define quailtracker_GpsFix_pps_synced_tag       7
#define quailtracker_GpsFix_pps_count_tag        8
#define quailtracker_GpsFix_utc_time_tag         9
#define quailtracker_AudioLevel_peak_tag         1
#define quailtracker_AudioLevel_activity_pct_tag 2
#define quailtracker_AudioLevel_clip_count_tag   3
#define quailtracker_AudioLevel_buf_used_tag     4
#define quailtracker_AudioLevel_buf_capacity_tag 5
#define quailtracker_Detection_species_tag       1
#define quailtracker_Detection_confidence_tag    2
#define quailtracker_Detection_utc_time_tag      3
#define quailtracker_Detection_window_sample_tag 4
#define quailtracker_RecordingState_active_tag   1
#define quailtracker_RecordingState_filename_tag 2
#define quailtracker_RecordingState_bytes_written_tag 3
#define quailtracker_RecordingState_duration_s_tag 4
#define quailtracker_RecordingState_overruns_tag 5
#define quailtracker_RecordingState_sd_free_kb_tag 6
#define quailtracker_LogLine_text_tag            1
#define quailtracker_Command_type_tag            1
#define quailtracker_CommandAck_type_tag         1
#define quailtracker_CommandAck_success_tag      2
#define quailtracker_CommandAck_error_tag        3
#define quailtracker_Subscribe_topic_tag         1
#define quailtracker_Subscribe_interval_ms_tag   2
#define quailtracker_Unsubscribe_topic_tag       1
#define quailtracker_TimeWindow_start_hhmm_tag   1
#define quailtracker_TimeWindow_end_hhmm_tag     2
#define quailtracker_Config_gain_tag             1
#define quailtracker_Config_bpf_low_hz_tag       2
#define quailtracker_Config_bpf_high_hz_tag      3
#define quailtracker_Config_sample_rate_tag      4
#define quailtracker_Config_rec_format_tag       5
#define quailtracker_Config_station_id_tag       10
#define quailtracker_Config_trig_enabled_tag     20
#define quailtracker_Config_trig_db_tag          21
#define quailtracker_Config_trig_pre_s_tag       22
#define quailtracker_Config_trig_post_s_tag      23
#define quailtracker_Config_low_bat_pct_tag      30
#define quailtracker_Config_auto_stop_tag        31
#define quailtracker_Config_act_mode_tag         40
#define quailtracker_Config_act_min_pct_tag      41
#define quailtracker_Config_act_max_pct_tag      42
#define quailtracker_Config_act_hold_s_tag       43
#define quailtracker_Config_sunrise_enabled_tag  50
#define quailtracker_Config_sunrise_before_tag   51
#define quailtracker_Config_sunrise_after_tag    52
#define quailtracker_Config_sunset_enabled_tag   53
#define quailtracker_Config_sunset_before_tag    54
#define quailtracker_Config_sunset_after_tag     55
#define quailtracker_Config_windows_tag          56
#define quailtracker_Config_mission_mode_tag     60
#define quailtracker_Config_det_threshold_tag    61
#define quailtracker_Config_det_step_s_tag       62
#define quailtracker_Config_survey_lat_e7_tag    70
#define quailtracker_Config_survey_lon_e7_tag    71
#define quailtracker_Config_survey_alt_mm_tag    72
#define quailtracker_Config_survey_count_tag     73
#define quailtracker_SetConfig_gain_tag          1
#define quailtracker_SetConfig_bpf_low_hz_tag    2
#define quailtracker_SetConfig_bpf_high_hz_tag   3
#define quailtracker_SetConfig_rec_format_tag    5
#define quailtracker_SetConfig_station_id_tag    10
#define quailtracker_SetConfig_trig_enabled_tag  20
#define quailtracker_SetConfig_trig_db_tag       21
#define quailtracker_SetConfig_trig_pre_s_tag    22
#define quailtracker_SetConfig_trig_post_s_tag   23
#define quailtracker_SetConfig_low_bat_pct_tag   30
#define quailtracker_SetConfig_auto_stop_tag     31
#define quailtracker_SetConfig_act_mode_tag      40
#define quailtracker_SetConfig_act_min_pct_tag   41
#define quailtracker_SetConfig_act_max_pct_tag   42
#define quailtracker_SetConfig_act_hold_s_tag    43
#define quailtracker_SetConfig_sunrise_enabled_tag 50
#define quailtracker_SetConfig_sunrise_before_tag 51
#define quailtracker_SetConfig_sunrise_after_tag 52
#define quailtracker_SetConfig_sunset_enabled_tag 53
#define quailtracker_SetConfig_sunset_before_tag 54
#define quailtracker_SetConfig_sunset_after_tag  55
#define quailtracker_SetConfig_windows_tag       56
#define quailtracker_SetConfig_mission_mode_tag  60
#define quailtracker_SetConfig_det_threshold_tag 61
#define quailtracker_SetConfig_det_step_s_tag    62
#define quailtracker_OtaBegin_size_bytes_tag     1
#define quailtracker_OtaBegin_crc32_tag          2
#define quailtracker_OtaData_chunk_tag           1
#define quailtracker_OtaStatus_state_tag         1
#define quailtracker_OtaStatus_bytes_received_tag 2
#define quailtracker_OtaStatus_pages_written_tag 3
#define quailtracker_OtaStatus_pages_total_tag   4

/* Struct field encoding specification for nanopb */
#define quailtracker_Status_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   battery_mv,        1) \
X(a, STATIC,   SINGULAR, UINT32,   battery_pct,       2) \
X(a, STATIC,   SINGULAR, BOOL,     ble_ready,        10) \
X(a, STATIC,   SINGULAR, STRING,   ble_name,         11) \
X(a, STATIC,   SINGULAR, BOOL,     sd_mounted,       20) \
X(a, STATIC,   SINGULAR, UINT32,   sd_total_kb,      21) \
X(a, STATIC,   SINGULAR, UINT32,   sd_free_kb,       22) \
X(a, STATIC,   SINGULAR, BOOL,     recording,        30) \
X(a, STATIC,   SINGULAR, STRING,   rec_filename,     31) \
X(a, STATIC,   SINGULAR, UINT32,   rec_bytes,        32) \
X(a, STATIC,   SINGULAR, UINT32,   rec_duration_s,   33) \
X(a, STATIC,   SINGULAR, UINT32,   rec_overruns,     34) \
X(a, STATIC,   SINGULAR, UINT32,   rec_format,       35) \
X(a, STATIC,   SINGULAR, BOOL,     det_active,       40) \
X(a, STATIC,   SINGULAR, UINT32,   det_windows,      41) \
X(a, STATIC,   SINGULAR, UINT32,   det_hits,         42) \
X(a, STATIC,   SINGULAR, STRING,   det_last_species,  43) \
X(a, STATIC,   SINGULAR, BOOL,     model_loaded,     44) \
X(a, STATIC,   SINGULAR, UINT32,   model_size,       45) \
X(a, STATIC,   SINGULAR, UINT32,   model_labels,     46) \
X(a, STATIC,   SINGULAR, INT32,    temperature_c100,  50) \
X(a, STATIC,   SINGULAR, UINT32,   humidity_rh100,   51) \
X(a, STATIC,   SINGULAR, STRING,   firmware_version,  60) \
X(a, STATIC,   SINGULAR, STRING,   station_id,       61)
#define quailtracker_Status_CALLBACK NULL
#define quailtracker_Status_DEFAULT NULL

#define quailtracker_GpsFix_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     valid,             1) \
X(a, STATIC,   SINGULAR, UINT32,   satellites,        2) \
X(a, STATIC,   SINGULAR, INT32,    latitude_e7,       3) \
X(a, STATIC,   SINGULAR, INT32,    longitude_e7,      4) \
X(a, STATIC,   SINGULAR, INT32,    altitude_mm,       5) \
X(a, STATIC,   SINGULAR, UINT32,   fix_type,          6) \
X(a, STATIC,   SINGULAR, BOOL,     pps_synced,        7) \
X(a, STATIC,   SINGULAR, UINT32,   pps_count,         8) \
X(a, STATIC,   SINGULAR, STRING,   utc_time,          9)
#define quailtracker_GpsFix_CALLBACK NULL
#define quailtracker_GpsFix_DEFAULT NULL

#define quailtracker_AudioLevel_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   peak,              1) \
X(a, STATIC,   SINGULAR, UINT32,   activity_pct,      2) \
X(a, STATIC,   SINGULAR, UINT32,   clip_count,        3) \
X(a, STATIC,   SINGULAR, UINT32,   buf_used,          4) \
X(a, STATIC,   SINGULAR, UINT32,   buf_capacity,      5)
#define quailtracker_AudioLevel_CALLBACK NULL
#define quailtracker_AudioLevel_DEFAULT NULL

#define quailtracker_Detection_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   species,           1) \
X(a, STATIC,   SINGULAR, UINT32,   confidence,        2) \
X(a, STATIC,   SINGULAR, STRING,   utc_time,          3) \
X(a, STATIC,   SINGULAR, UINT64,   window_sample,     4)
#define quailtracker_Detection_CALLBACK NULL
#define quailtracker_Detection_DEFAULT NULL

#define quailtracker_RecordingState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     active,            1) \
X(a, STATIC,   SINGULAR, STRING,   filename,          2) \
X(a, STATIC,   SINGULAR, UINT32,   bytes_written,     3) \
X(a, STATIC,   SINGULAR, UINT32,   duration_s,        4) \
X(a, STATIC,   SINGULAR, UINT32,   overruns,          5) \
X(a, STATIC,   SINGULAR, UINT32,   sd_free_kb,        6)
#define quailtracker_RecordingState_CALLBACK NULL
#define quailtracker_RecordingState_DEFAULT NULL

#define quailtracker_LogLine_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   text,              1)
#define quailtracker_LogLine_CALLBACK NULL
#define quailtracker_LogLine_DEFAULT NULL

#define quailtracker_Command_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1)
#define quailtracker_Command_CALLBACK NULL
#define quailtracker_Command_DEFAULT NULL

#define quailtracker_CommandAck_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, BOOL,     success,           2) \
X(a, STATIC,   SINGULAR, STRING,   error,             3)
#define quailtracker_CommandAck_CALLBACK NULL
#define quailtracker_CommandAck_DEFAULT NULL

#define quailtracker_Subscribe_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   topic,             1) \
X(a, STATIC,   SINGULAR, UINT32,   interval_ms,       2)
#define quailtracker_Subscribe_CALLBACK NULL
#define quailtracker_Subscribe_DEFAULT NULL

#define quailtracker_Unsubscribe_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   topic,             1)
#define quailtracker_Unsubscribe_CALLBACK NULL
#define quailtracker_Unsubscribe_DEFAULT NULL

#define quailtracker_TimeWindow_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   start_hhmm,        1) \
X(a, STATIC,   SINGULAR, UINT32,   end_hhmm,          2)
#define quailtracker_TimeWindow_CALLBACK NULL
#define quailtracker_TimeWindow_DEFAULT NULL

#define quailtracker_Config_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   gain,              1) \
X(a, STATIC,   SINGULAR, UINT32,   bpf_low_hz,        2) \
X(a, STATIC,   SINGULAR, UINT32,   bpf_high_hz,       3) \
X(a, STATIC,   SINGULAR, UINT32,   sample_rate,       4) \
X(a, STATIC,   SINGULAR, UINT32,   rec_format,        5) \
X(a, STATIC,   SINGULAR, STRING,   station_id,       10) \
X(a, STATIC,   SINGULAR, BOOL,     trig_enabled,     20) \
X(a, STATIC,   SINGULAR, INT32,    trig_db,          21) \
X(a, STATIC,   SINGULAR, UINT32,   trig_pre_s,       22) \
X(a, STATIC,   SINGULAR, UINT32,   trig_post_s,      23) \
X(a, STATIC,   SINGULAR, UINT32,   low_bat_pct,      30) \
X(a, STATIC,   SINGULAR, BOOL,     auto_stop,        31) \
X(a, STATIC,   SINGULAR, UINT32,   act_mode,         40) \
X(a, STATIC,   SINGULAR, UINT32,   act_min_pct,      41) \
X(a, STATIC,   SINGULAR, UINT32,   act_max_pct,      42) \
X(a, STATIC,   SINGULAR, UINT32,   act_hold_s,       43) \
X(a, STATIC,   SINGULAR, BOOL,     sunrise_enabled,  50) \
X(a, STATIC,   SINGULAR, UINT32,   sunrise_before,   51) \
X(a, STATIC,   SINGULAR, UINT32,   sunrise_after,    52) \
X(a, STATIC,   SINGULAR, BOOL,     sunset_enabled,   53) \
X(a, STATIC,   SINGULAR, UINT32,   sunset_before,    54) \
X(a, STATIC,   SINGULAR, UINT32,   sunset_after,     55) \
X(a, STATIC,   REPEATED, MESSAGE,  windows,          56) \
X(a, STATIC,   SINGULAR, UINT32,   mission_mode,     60) \
X(a, STATIC,   SINGULAR, UINT32,   det_threshold,    61) \
X(a, STATIC,   SINGULAR, UINT32,   det_step_s,       62) \
X(a, STATIC,   SINGULAR, INT32,    survey_lat_e7,    70) \
X(a, STATIC,   SINGULAR, INT32,    survey_lon_e7,    71) \
X(a, STATIC,   SINGULAR, INT32,    survey_alt_mm,    72) \
X(a, STATIC,   SINGULAR, UINT32,   survey_count,     73)
#define quailtracker_Config_CALLBACK NULL
#define quailtracker_Config_DEFAULT NULL
#define quailtracker_Config_windows_MSGTYPE quailtracker_TimeWindow

#define quailtracker_SetConfig_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   gain,              1) \
X(a, STATIC,   OPTIONAL, UINT32,   bpf_low_hz,        2) \
X(a, STATIC,   OPTIONAL, UINT32,   bpf_high_hz,       3) \
X(a, STATIC,   OPTIONAL, UINT32,   rec_format,        5) \
X(a, STATIC,   OPTIONAL, STRING,   station_id,       10) \
X(a, STATIC,   OPTIONAL, BOOL,     trig_enabled,     20) \
X(a, STATIC,   OPTIONAL, INT32,    trig_db,          21) \
X(a, STATIC,   OPTIONAL, UINT32,   trig_pre_s,       22) \
X(a, STATIC,   OPTIONAL, UINT32,   trig_post_s,      23) \
X(a, STATIC,   OPTIONAL, UINT32,   low_bat_pct,      30) \
X(a, STATIC,   OPTIONAL, BOOL,     auto_stop,        31) \
X(a, STATIC,   OPTIONAL, UINT32,   act_mode,         40) \
X(a, STATIC,   OPTIONAL, UINT32,   act_min_pct,      41) \
X(a, STATIC,   OPTIONAL, UINT32,   act_max_pct,      42) \
X(a, STATIC,   OPTIONAL, UINT32,   act_hold_s,       43) \
X(a, STATIC,   OPTIONAL, BOOL,     sunrise_enabled,  50) \
X(a, STATIC,   OPTIONAL, UINT32,   sunrise_before,   51) \
X(a, STATIC,   OPTIONAL, UINT32,   sunrise_after,    52) \
X(a, STATIC,   OPTIONAL, BOOL,     sunset_enabled,   53) \
X(a, STATIC,   OPTIONAL, UINT32,   sunset_before,    54) \
X(a, STATIC,   OPTIONAL, UINT32,   sunset_after,     55) \
X(a, STATIC,   REPEATED, MESSAGE,  windows,          56) \
X(a, STATIC,   OPTIONAL, UINT32,   mission_mode,     60) \
X(a, STATIC,   OPTIONAL, UINT32,   det_threshold,    61) \
X(a, STATIC,   OPTIONAL, UINT32,   det_step_s,       62)
#define quailtracker_SetConfig_CALLBACK NULL
#define quailtracker_SetConfig_DEFAULT NULL
#define quailtracker_SetConfig_windows_MSGTYPE quailtracker_TimeWindow

#define quailtracker_OtaBegin_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   size_bytes,        1) \
X(a, STATIC,   SINGULAR, UINT32,   crc32,             2)
#define quailtracker_OtaBegin_CALLBACK NULL
#define quailtracker_OtaBegin_DEFAULT NULL

#define quailtracker_OtaData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    chunk,             1)
#define quailtracker_OtaData_CALLBACK NULL
#define quailtracker_OtaData_DEFAULT NULL

#define quailtracker_OtaEnd_FIELDLIST(X, a) \

#define quailtracker_OtaEnd_CALLBACK NULL
#define quailtracker_OtaEnd_DEFAULT NULL

#define quailtracker_OtaCommit_FIELDLIST(X, a) \

#define quailtracker_OtaCommit_CALLBACK NULL
#define quailtracker_OtaCommit_DEFAULT NULL

#define quailtracker_OtaAbort_FIELDLIST(X, a) \

#define quailtracker_OtaAbort_CALLBACK NULL
#define quailtracker_OtaAbort_DEFAULT NULL

#define quailtracker_OtaRollback_FIELDLIST(X, a) \

#define quailtracker_OtaRollback_CALLBACK NULL
#define quailtracker_OtaRollback_DEFAULT NULL

#define quailtracker_OtaStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   state,             1) \
X(a, STATIC,   SINGULAR, UINT32,   bytes_received,    2) \
X(a, STATIC,   SINGULAR, UINT32,   pages_written,     3) \
X(a, STATIC,   SINGULAR, UINT32,   pages_total,       4)
#define quailtracker_OtaStatus_CALLBACK NULL
#define quailtracker_OtaStatus_DEFAULT NULL

extern const pb_msgdesc_t quailtracker_Status_msg;
extern const pb_msgdesc_t quailtracker_GpsFix_msg;
extern const pb_msgdesc_t quailtracker_AudioLevel_msg;
extern const pb_msgdesc_t quailtracker_Detection_msg;
extern const pb_msgdesc_t quailtracker_RecordingState_msg;
extern const pb_msgdesc_t quailtracker_LogLine_msg;
extern const pb_msgdesc_t quailtracker_Command_msg;
extern const pb_msgdesc_t quailtracker_CommandAck_msg;
extern const pb_msgdesc_t quailtracker_Subscribe_msg;
extern const pb_msgdesc_t quailtracker_Unsubscribe_msg;
extern const pb_msgdesc_t quailtracker_TimeWindow_msg;
extern const pb_msgdesc_t quailtracker_Config_msg;
extern const pb_msgdesc_t quailtracker_SetConfig_msg;
extern const pb_msgdesc_t quailtracker_OtaBegin_msg;
extern const pb_msgdesc_t quailtracker_OtaData_msg;
extern const pb_msgdesc_t quailtracker_OtaEnd_msg;
extern const pb_msgdesc_t quailtracker_OtaCommit_msg;
extern const pb_msgdesc_t quailtracker_OtaAbort_msg;
extern const pb_msgdesc_t quailtracker_OtaRollback_msg;
extern const pb_msgdesc_t quailtracker_OtaStatus_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define quailtracker_Status_fields &quailtracker_Status_msg
#define quailtracker_GpsFix_fields &quailtracker_GpsFix_msg
#define quailtracker_AudioLevel_fields &quailtracker_AudioLevel_msg
#define quailtracker_Detection_fields &quailtracker_Detection_msg
#define quailtracker_RecordingState_fields &quailtracker_RecordingState_msg
#define quailtracker_LogLine_fields &quailtracker_LogLine_msg
#define quailtracker_Command_fields &quailtracker_Command_msg
#define quailtracker_CommandAck_fields &quailtracker_CommandAck_msg
#define quailtracker_Subscribe_fields &quailtracker_Subscribe_msg
#define quailtracker_Unsubscribe_fields &quailtracker_Unsubscribe_msg
#define quailtracker_TimeWindow_fields &quailtracker_TimeWindow_msg
#define quailtracker_Config_fields &quailtracker_Config_msg
#define quailtracker_SetConfig_fields &quailtracker_SetConfig_msg
#define quailtracker_OtaBegin_fields &quailtracker_OtaBegin_msg
#define quailtracker_OtaData_fields &quailtracker_OtaData_msg
#define quailtracker_OtaEnd_fields &quailtracker_OtaEnd_msg
#define quailtracker_OtaCommit_fields &quailtracker_OtaCommit_msg
#define quailtracker_OtaAbort_fields &quailtracker_OtaAbort_msg
#define quailtracker_OtaRollback_fields &quailtracker_OtaRollback_msg
#define quailtracker_OtaStatus_fields &quailtracker_OtaStatus_msg

/* Maximum encoded size of messages (where known) */
#define QUAILTRACKER_QUAILTRACKER_PB_H_MAX_SIZE  quailtracker_Config_size
#define quailtracker_AudioLevel_size             30
#define quailtracker_CommandAck_size             37
#define quailtracker_Command_size                2
#define quailtracker_Config_size                 332
#define quailtracker_Detection_size              67
#define quailtracker_GpsFix_size                 72
#define quailtracker_LogLine_size                130
#define quailtracker_OtaAbort_size               0
#define quailtracker_OtaBegin_size               12
#define quailtracker_OtaCommit_size              0
#define quailtracker_OtaData_size                131
#define quailtracker_OtaEnd_size                 0
#define quailtracker_OtaRollback_size            0
#define quailtracker_OtaStatus_size              24
#define quailtracker_RecordingState_size         67
#define quailtracker_SetConfig_size              283
#define quailtracker_Status_size                 244
#define quailtracker_Subscribe_size              12
#define quailtracker_TimeWindow_size             12
#define quailtracker_Unsubscribe_size            6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
