"""Export trained model to int8 TFLite and C headers for STM32.

Usage:
    python export.py --model-dir output --data-dir /path/to/exported_clips
"""

import argparse
import json
import os
import textwrap

import librosa
import numpy as np
import tensorflow as tf


def convert_to_tflite_int8(model_or_path, calibration_data_path, output_path):
    """Full int8 quantization (weights AND activations).

    Args:
        model_or_path: Keras model object or path to weights file.
        calibration_data_path: Path to calibration_data.npy.
        output_path: Path for output .tflite file.

    Returns:
        Size of the TFLite model in bytes.
    """
    if isinstance(model_or_path, str):
        model = tf.keras.models.load_model(model_or_path, compile=False)
    else:
        model = model_or_path
    cal_data = np.load(calibration_data_path)

    def representative_dataset():
        for i in range(len(cal_data)):
            sample = cal_data[i][np.newaxis, ..., np.newaxis].astype(np.float32)
            yield [sample]

    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = representative_dataset
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8

    tflite_model = converter.convert()

    with open(output_path, "wb") as f:
        f.write(tflite_model)

    size_kb = len(tflite_model) / 1024
    print(f"Saved TFLite model: {output_path} ({size_kb:.1f} KB)")
    return len(tflite_model)


def generate_model_header(tflite_path, header_path):
    """Generate C header with model bytes as const uint8_t array.

    Args:
        tflite_path: Path to .tflite file.
        header_path: Output .h file path.
    """
    with open(tflite_path, "rb") as f:
        model_bytes = f.read()

    model_size = len(model_bytes)

    # Format as C array
    hex_lines = []
    for i in range(0, len(model_bytes), 12):
        chunk = model_bytes[i:i + 12]
        hex_str = ", ".join(f"0x{b:02x}" for b in chunk)
        hex_lines.append(f"  {hex_str},")

    hex_content = "\n".join(hex_lines)

    header = textwrap.dedent(f"""\
        /* Auto-generated by QuailTracker training pipeline — do not edit */
        #ifndef QUAIL_MODEL_H
        #define QUAIL_MODEL_H

        #include <stdint.h>

        #define QUAIL_MODEL_SIZE {model_size}

        alignas(16) const uint8_t quail_model_data[QUAIL_MODEL_SIZE] = {{
        {hex_content}
        }};

        #endif /* QUAIL_MODEL_H */
    """)

    with open(header_path, "w") as f:
        f.write(header)

    print(f"Saved model header: {header_path}")


def generate_mel_config_header(metadata_path, header_path):
    """Generate C header with mel parameters, normalization constants, and class labels.

    Args:
        metadata_path: Path to model_metadata.json.
        header_path: Output .h file path.
    """
    with open(metadata_path, "r") as f:
        metadata = json.load(f)

    ac = metadata["audio_config"]
    labels = metadata["labels"]
    mel_min = metadata["mel_min"]
    mel_max = metadata["mel_max"]

    # Format label strings as C array
    label_strings = ",\n".join(f'  "{label}"' for label in labels)

    header = textwrap.dedent(f"""\
        /* Auto-generated by QuailTracker training pipeline — do not edit */
        #ifndef MEL_CONFIG_H
        #define MEL_CONFIG_H

        #include <stdint.h>

        /* Audio parameters — must match Python training exactly */
        #define MEL_SAMPLE_RATE   {ac['sample_rate']}
        #define MEL_N_FFT         {ac['n_fft']}
        #define MEL_HOP_LENGTH    {ac['hop_length']}
        #define MEL_N_MELS        {ac['n_mels']}
        #define MEL_N_FRAMES      {ac['n_frames']}
        #define MEL_FMIN          {ac['fmin']:.1f}f
        #define MEL_FMAX          {ac['fmax']:.1f}f

        /* Normalization constants from training data */
        #define MEL_NORM_MIN      {mel_min:.6f}f
        #define MEL_NORM_MAX      {mel_max:.6f}f
        #define MEL_NORM_RANGE    {mel_max - mel_min:.6f}f

        /* Class labels */
        #define NUM_CLASSES       {len(labels)}

        static const char* const class_labels[NUM_CLASSES] = {{
        {label_strings}
        }};

        #endif /* MEL_CONFIG_H */
    """)

    with open(header_path, "w") as f:
        f.write(header)

    print(f"Saved mel config header: {header_path}")


def generate_mel_filterbank_header(metadata_path, header_path):
    """Generate C header with sparse mel filterbank coefficients.

    Each mel bin has a variable number of contributing FFT bins.
    Stored as sparse (index, weight) pairs for efficient fixed-point
    multiply-accumulate on STM32 (no full NxM matrix needed).

    Args:
        metadata_path: Path to model_metadata.json.
        header_path: Output .h file path.
    """
    with open(metadata_path, "r") as f:
        metadata = json.load(f)

    ac = metadata["audio_config"]
    sr = ac["sample_rate"]
    n_fft = ac["n_fft"]
    n_mels = ac["n_mels"]
    fmin = ac["fmin"]
    fmax = ac["fmax"]

    # Generate mel filterbank using librosa (matches training exactly)
    mel_fb = librosa.filters.mel(
        sr=sr, n_fft=n_fft, n_mels=n_mels,
        fmin=fmin, fmax=fmax, norm="slaney",
    )  # shape: (n_mels, n_fft//2 + 1)

    # Convert to int16 weights (Q15-ish: max weight → 32767)
    max_val = mel_fb.max()
    if max_val > 0:
        scale = 32767.0 / max_val
    else:
        scale = 1.0

    lines = []
    lines.append("/* Auto-generated by QuailTracker training pipeline — do not edit */")
    lines.append("#ifndef MEL_FILTERBANK_H")
    lines.append("#define MEL_FILTERBANK_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append(f"#define MEL_FB_N_MELS  {n_mels}")
    lines.append(f"#define MEL_FB_N_FFT   {n_fft}")
    lines.append(f"#define MEL_FB_N_BINS  {n_fft // 2 + 1}")
    lines.append(f"#define MEL_FB_SCALE   {scale:.6f}f")
    lines.append("")

    # For each mel bin, emit sparse (fft_bin_index, int16_weight) pairs
    for m in range(n_mels):
        nonzero = np.nonzero(mel_fb[m])[0]
        weights = (mel_fb[m][nonzero] * scale).astype(np.int16)

        indices_str = ", ".join(str(int(idx)) for idx in nonzero)
        weights_str = ", ".join(str(int(w)) for w in weights)

        lines.append(f"/* Mel bin {m}: {len(nonzero)} coefficients */")
        lines.append(f"static const uint16_t mel_fb_idx_{m}[] = {{ {indices_str} }};")
        lines.append(f"static const int16_t  mel_fb_wt_{m}[]  = {{ {weights_str} }};")
        lines.append("")

    # Bin count array
    counts = []
    for m in range(n_mels):
        counts.append(str(len(np.nonzero(mel_fb[m])[0])))
    lines.append("static const uint8_t mel_fb_count[MEL_FB_N_MELS] = {")
    lines.append("  " + ", ".join(counts))
    lines.append("};")
    lines.append("")

    # Index pointer array
    lines.append("static const uint16_t* const mel_fb_indices[MEL_FB_N_MELS] = {")
    lines.append("  " + ", ".join(f"mel_fb_idx_{m}" for m in range(n_mels)))
    lines.append("};")
    lines.append("")

    # Weight pointer array
    lines.append("static const int16_t* const mel_fb_weights[MEL_FB_N_MELS] = {")
    lines.append("  " + ", ".join(f"mel_fb_wt_{m}" for m in range(n_mels)))
    lines.append("};")
    lines.append("")
    lines.append("#endif /* MEL_FILTERBANK_H */")

    with open(header_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Saved mel filterbank header: {header_path}")


def generate_model_config_json(metadata_path, tflite_path, json_path):
    """Generate model_config.json for BLE deployment to device.

    Contains mel params, normalization constants, and class labels so
    firmware can configure inference without a rebuild.

    Args:
        metadata_path: Path to model_metadata.json from training.
        tflite_path: Path to .tflite file (for size info).
        json_path: Output .json file path.
    """
    with open(metadata_path, "r") as f:
        metadata = json.load(f)

    tflite_size = os.path.getsize(tflite_path)

    config_json = {
        "model_file": os.path.basename(tflite_path),
        "model_size_bytes": tflite_size,
        "audio_config": metadata["audio_config"],
        "normalization": {
            "mel_min": metadata["mel_min"],
            "mel_max": metadata["mel_max"],
        },
        "labels": metadata["labels"],
        "num_classes": metadata["num_classes"],
        "training_info": {
            "total_clips": metadata.get("total_clips", 0),
            "epochs_trained": metadata.get("epochs_trained", 0),
            "best_val_auc": metadata.get("best_val_auc", 0),
        },
    }

    with open(json_path, "w") as f:
        json.dump(config_json, f, indent=2)

    print(f"Saved model config JSON: {json_path}")
    return config_json


def main():
    parser = argparse.ArgumentParser(description="Export model to TFLite + C headers")
    parser.add_argument(
        "--model-dir", required=True,
        help="Directory containing best_model.h5 and calibration_data.npy",
    )
    parser.add_argument(
        "--data-dir", required=True,
        help="Path to exported clips directory (unused, kept for workflow consistency)",
    )
    args = parser.parse_args()

    weights_path = os.path.join(args.model_dir, "best_model.weights.h5")
    cal_path = os.path.join(args.model_dir, "calibration_data.npy")
    metadata_path = os.path.join(args.model_dir, "model_metadata.json")

    for path, name in [
        (weights_path, "best_model.weights.h5"),
        (cal_path, "calibration_data.npy"),
        (metadata_path, "model_metadata.json"),
    ]:
        if not os.path.exists(path):
            print(f"Error: {name} not found at {path}")
            print("Run train.py first.")
            return

    # Rebuild model and load weights (avoids loss serialization bug)
    from config import Config
    from model import build_model
    with open(metadata_path, "r") as f:
        metadata = json.load(f)
    config = Config()
    model = build_model(config, metadata["num_classes"])
    model.load_weights(weights_path)

    # Convert to int8 TFLite
    tflite_path = os.path.join(args.model_dir, "quail_model.tflite")
    model_size = convert_to_tflite_int8(model, cal_path, tflite_path)

    if model_size > 200 * 1024:
        print(f"WARNING: Model size ({model_size / 1024:.1f} KB) exceeds 200 KB flash budget!")

    # Generate C headers
    generate_model_header(
        tflite_path,
        os.path.join(args.model_dir, "quail_model.h"),
    )
    generate_mel_config_header(
        metadata_path,
        os.path.join(args.model_dir, "mel_config.h"),
    )
    generate_mel_filterbank_header(
        metadata_path,
        os.path.join(args.model_dir, "mel_filterbank.h"),
    )

    # Generate JSON config for BLE deployment
    generate_model_config_json(
        metadata_path,
        tflite_path,
        os.path.join(args.model_dir, "model_config.json"),
    )

    print(f"\nExport complete! Files in {args.model_dir}/:")
    print(f"  quail_model.tflite  ({model_size / 1024:.1f} KB)")
    print(f"  quail_model.h       (C header with model bytes)")
    print(f"  mel_config.h        (C header with mel params + labels)")
    print(f"  mel_filterbank.h    (C header with sparse mel filterbank)")
    print(f"  model_config.json   (JSON config for BLE deployment)")
    print(f"\nCopy headers to stm32/QuailTracker_U575/Core/Inc/ for firmware integration.")
    print(f"Copy .tflite + model_config.json to SD card /model/ directory.")


if __name__ == "__main__":
    main()
