"""Export trained model to int8 TFLite and C headers for STM32.

Usage:
    python export.py --model-dir output --data-dir /path/to/exported_clips
"""

import argparse
import json
import os
import textwrap

import numpy as np
import tensorflow as tf


def convert_to_tflite_int8(model_path, calibration_data_path, output_path):
    """Full int8 quantization (weights AND activations).

    Args:
        model_path: Path to best_model.keras.
        calibration_data_path: Path to calibration_data.npy.
        output_path: Path for output .tflite file.

    Returns:
        Size of the TFLite model in bytes.
    """
    model = tf.keras.models.load_model(model_path)
    cal_data = np.load(calibration_data_path)

    def representative_dataset():
        for i in range(len(cal_data)):
            sample = cal_data[i][np.newaxis, ..., np.newaxis].astype(np.float32)
            yield [sample]

    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = representative_dataset
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8

    tflite_model = converter.convert()

    with open(output_path, "wb") as f:
        f.write(tflite_model)

    size_kb = len(tflite_model) / 1024
    print(f"Saved TFLite model: {output_path} ({size_kb:.1f} KB)")
    return len(tflite_model)


def generate_model_header(tflite_path, header_path):
    """Generate C header with model bytes as const uint8_t array.

    Args:
        tflite_path: Path to .tflite file.
        header_path: Output .h file path.
    """
    with open(tflite_path, "rb") as f:
        model_bytes = f.read()

    model_size = len(model_bytes)

    # Format as C array
    hex_lines = []
    for i in range(0, len(model_bytes), 12):
        chunk = model_bytes[i:i + 12]
        hex_str = ", ".join(f"0x{b:02x}" for b in chunk)
        hex_lines.append(f"  {hex_str},")

    hex_content = "\n".join(hex_lines)

    header = textwrap.dedent(f"""\
        /* Auto-generated by QuailTracker training pipeline — do not edit */
        #ifndef QUAIL_MODEL_H
        #define QUAIL_MODEL_H

        #include <stdint.h>

        #define QUAIL_MODEL_SIZE {model_size}

        alignas(16) const uint8_t quail_model_data[QUAIL_MODEL_SIZE] = {{
        {hex_content}
        }};

        #endif /* QUAIL_MODEL_H */
    """)

    with open(header_path, "w") as f:
        f.write(header)

    print(f"Saved model header: {header_path}")


def generate_mel_config_header(metadata_path, header_path):
    """Generate C header with mel parameters, normalization constants, and class labels.

    Args:
        metadata_path: Path to model_metadata.json.
        header_path: Output .h file path.
    """
    with open(metadata_path, "r") as f:
        metadata = json.load(f)

    ac = metadata["audio_config"]
    labels = metadata["labels"]
    mel_min = metadata["mel_min"]
    mel_max = metadata["mel_max"]

    # Format label strings as C array
    label_strings = ",\n".join(f'  "{label}"' for label in labels)

    header = textwrap.dedent(f"""\
        /* Auto-generated by QuailTracker training pipeline — do not edit */
        #ifndef MEL_CONFIG_H
        #define MEL_CONFIG_H

        #include <stdint.h>

        /* Audio parameters — must match Python training exactly */
        #define MEL_SAMPLE_RATE   {ac['sample_rate']}
        #define MEL_N_FFT         {ac['n_fft']}
        #define MEL_HOP_LENGTH    {ac['hop_length']}
        #define MEL_N_MELS        {ac['n_mels']}
        #define MEL_N_FRAMES      {ac['n_frames']}
        #define MEL_FMIN          {ac['fmin']:.1f}f
        #define MEL_FMAX          {ac['fmax']:.1f}f

        /* Normalization constants from training data */
        #define MEL_NORM_MIN      {mel_min:.6f}f
        #define MEL_NORM_MAX      {mel_max:.6f}f
        #define MEL_NORM_RANGE    {mel_max - mel_min:.6f}f

        /* Class labels */
        #define NUM_CLASSES       {len(labels)}

        static const char* const class_labels[NUM_CLASSES] = {{
        {label_strings}
        }};

        #endif /* MEL_CONFIG_H */
    """)

    with open(header_path, "w") as f:
        f.write(header)

    print(f"Saved mel config header: {header_path}")


def main():
    parser = argparse.ArgumentParser(description="Export model to TFLite + C headers")
    parser.add_argument(
        "--model-dir", required=True,
        help="Directory containing best_model.keras and calibration_data.npy",
    )
    parser.add_argument(
        "--data-dir", required=True,
        help="Path to exported clips directory (unused, kept for workflow consistency)",
    )
    args = parser.parse_args()

    model_path = os.path.join(args.model_dir, "best_model.keras")
    cal_path = os.path.join(args.model_dir, "calibration_data.npy")
    metadata_path = os.path.join(args.model_dir, "model_metadata.json")

    for path, name in [
        (model_path, "best_model.keras"),
        (cal_path, "calibration_data.npy"),
        (metadata_path, "model_metadata.json"),
    ]:
        if not os.path.exists(path):
            print(f"Error: {name} not found at {path}")
            print("Run train.py first.")
            return

    # Convert to int8 TFLite
    tflite_path = os.path.join(args.model_dir, "quail_model.tflite")
    model_size = convert_to_tflite_int8(model_path, cal_path, tflite_path)

    if model_size > 200 * 1024:
        print(f"WARNING: Model size ({model_size / 1024:.1f} KB) exceeds 200 KB flash budget!")

    # Generate C headers
    generate_model_header(
        tflite_path,
        os.path.join(args.model_dir, "quail_model.h"),
    )
    generate_mel_config_header(
        metadata_path,
        os.path.join(args.model_dir, "mel_config.h"),
    )

    print(f"\nExport complete! Files in {args.model_dir}/:")
    print(f"  quail_model.tflite  ({model_size / 1024:.1f} KB)")
    print(f"  quail_model.h       (C header with model bytes)")
    print(f"  mel_config.h        (C header with mel params + labels)")
    print(f"\nCopy headers to stm32/QuailTracker_U575/Core/Inc/ for firmware integration.")


if __name__ == "__main__":
    main()
